using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoGeneratedApiClient.Models
{
	public class AddWeatherData
	{
		public double Temperature { get; set; }
		public string Region { get; set; }
		public TemperatureType Kind { get; set; }
	}
}
