using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoGeneratedApiClient.Models
{
	public enum TemperatureType
	{
		Celcium,
		Farengheit
	}
}
